spring:
  application:
    name: dubbo-registry-nacos-consumer-sample
demo:
  service:
    version: 1.0.0

nacos:
  host: 192.168.230.128
  port: 8848

dubbo:
  registry:
    address: nacos://${nacos.host}:${nacos.port}
    group: REi-GROUP
  provider:
    filter: tracing
  consumer:
    filter: tracing
    check: false
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: org.apache.dubbo.spring.boot.sample.consumer.service
zipkin:
  serviceName: consumer
  url: http://192.168.230.128:9411/api/v2/spans
  connectTimeout: 6000
  readTimeout: 6000
  flushInterval: 1
  compressionEnabled: true
server:
  port: 8088